### PR TITLE
Flatten components

### LINKED ISSUE #110: Refactor Components Into Unified Project Structure
Currently the project is subdivided into "components" with a distinct component for each deliverable Docker container (Channel, Controller, Dispatcher), and a separate "common" collection of utilities.  The code was organized this way due to limitations of prior build systems and is no longer required.  Working with these components, and the dependencies between them, is awkward and also not aligned with the eventing-contrib structure.  Therefore, we want to remove this componentization in favor of a flatter structure.  This will result in a single /vendor folder and set of Gopkg.toml making dep maintenance easier.  Likewise we will have a single Makefile which builds all three deliverables regardless of code changes (preferring simplicity over efficiency here).

### Acceptance Criteria
- Flat project structure with single Makefile, Gopkg.*, /vendor
- Makefile targets for prow still supported and building all 3 deliverables
- READMEs updated to reflect new layout
- All images function as they did before, unit tests passing, etc...
- Prow job converted to use new structure / Makefile - consolidate from 3 jobs to 1?

### PR DESCRIPTION
**Pull request by travis-minke-sap**

### CODE REVIEW

**Comment by tehcyx** [comment]
Trying out manual trigger.

/test all

**Review by phamilton — APPROVED** [review]
LGTM

**Pull request merged**
